# Generated by Django 5.2.6 on 2026-04-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.CharField(
                choices=[
                    ("reguler", "Reguler ( -3 hari)"),
                    ("kilat", "Kilat (1 hari)"),
                    ("express", "Express (6 jam)"),
                    ("express", "Express (3 jam)"),
                ],
                default="biasa",
                max_length=20,
            ),
        ),
    ]
