# Generated by Django 5.2.6 on 2026-06-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_service_duration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemType",
        ),
    ]
