# Generated by Django 5.2.6 on 2026-04-18 09:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordresetotp",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Reset Password OTP",
                "verbose_name_plural": "Reset Password OTP",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Pengguna",
                "verbose_name_plural": "Pengguna",
            },
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name="Sudah Digunakan"),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Tanggal Lahir"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                verbose_name="Foto Profil",
            ),
        ),
        migrations.AlterField(
            model_name="passwordresetotp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Waktu Dibuat"),
        ),
        migrations.AlterField(
            model_name="passwordresetotp",
            name="otp",
            field=models.CharField(max_length=6, verbose_name="Kode OTP"),
        ),
        migrations.AlterField(
            model_name="passwordresetotp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reset_otps",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pengguna",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Alamat"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_courier",
            field=models.BooleanField(default=False, verbose_name="Kurir"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=True, verbose_name="Pelanggan"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff_member",
            field=models.BooleanField(default=False, verbose_name="Staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Terverifikasi"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default=0,
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Nomor HP harus berupa angka dan minimal 10 digit",
                        regex="^[0-9]{10,15}$",
                    )
                ],
                verbose_name="Nomor WhatsApp",
            ),
            preserve_default=False,
        ),
    ]
