# Generated by Django 5.2.6 on 2026-04-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_passwordresetotp_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
    ]
