# Generated by Django 5.2.8 on 2025-12-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_promo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Promo",
        ),
    ]
