# Generated by Django 5.2.6 on 2026-05-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whatsapp_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
