# Generated by Django 5.2.6 on 2026-05-21 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_whatsapp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="whatsapp_id",
            new_name="wa_id",
        ),
    ]
