# Generated by Django 5.2.6 on 2026-04-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promo",
            old_name="discount",
            new_name="discount_amount",
        ),
    ]
