# Generated by Django 5.2.6 on 2026-05-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_discount_promo_discount_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[("delivery", "Diantar Kurir"), ("pickup", "Ambil Sendiri")],
                default="delivery",
                help_text="Apakah hasil laundry diantar kurir atau diambil sendiri?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Nominal diskon yang didapat",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_method",
            field=models.CharField(
                choices=[("pickup", "Dijemput Kurir"), ("dropoff", "Antar Sendiri")],
                default="pickup",
                help_text="Apakah laundry dijemput kurir atau diantar sendiri?",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total biaya pengiriman (bisa 1x atau 2x ongkir)",
                max_digits=12,
            ),
        ),
    ]
