# Generated by Django 5.2.6 on 2026-05-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_delivery_method_order_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="estimated_completion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Estimasi Selesai"
            ),
        ),
    ]
