# Generated by Django 5.2.6 on 2026-07-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_estimated_completion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="snap_token",
        ),
        migrations.RemoveField(
            model_name="order",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_proof",
            field=models.ImageField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Belum Dibayar"),
                    ("waiting_confirmation", "Menunggu Konfirmasi"),
                    ("paid", "Sudah Dibayar"),
                    ("rejected", "Ditolak"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
