# Generated by Django 5.2.6 on 2026-07-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_snap_token_remove_order_transaction_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=50)),
                ("qris_image", models.ImageField(upload_to="qris/")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
