# Generated by Django 5.2.8 on 2025-12-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_userpromo"),
    ]

    operations = [
        migrations.AddField(
            model_name="promo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="promo/"),
        ),
    ]
