# Generated by Django 5.2.6 on 2026-07-21 12:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_paymentsetting"),
        ("services", "0004_delete_itemtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpromo",
            options={"ordering": ["-assigned_at"]},
        ),
        migrations.AddField(
            model_name="laundryitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="laundryitem",
            name="description",
            field=models.TextField(blank=True, help_text="Deskripsi item"),
        ),
        migrations.AddField(
            model_name="laundryitem",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Apakah item masih aktif"
            ),
        ),
        migrations.AddField(
            model_name="laundryitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="notified_courier",
            field=models.BooleanField(
                default=False, help_text="Apakah notifikasi sudah dikirim ke kurir"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="paymentsetting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentsetting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="promo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userpromo",
            name="used_at",
            field=models.DateTimeField(
                blank=True, help_text="Tanggal promo digunakan", null=True
            ),
        ),
        migrations.AlterField(
            model_name="laundryitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="laundry_items/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="assigned_courier",
            field=models.ForeignKey(
                blank=True,
                help_text="Kurir yang ditugaskan untuk order ini",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cart_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Data keranjang saat order dibuat",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Diskon dalam persen",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="estimated_completion",
            field=models.DateTimeField(
                blank=True,
                help_text="Estimasi waktu selesai laundry",
                null=True,
                verbose_name="Estimasi Selesai",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="latitude",
            field=models.FloatField(help_text="Latitude lokasi pickup"),
        ),
        migrations.AlterField(
            model_name="order",
            name="longitude",
            field=models.FloatField(help_text="Longitude lokasi pickup"),
        ),
        migrations.AlterField(
            model_name="order",
            name="notified_customer",
            field=models.BooleanField(
                default=False, help_text="Apakah notifikasi sudah dikirim ke customer"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_date",
            field=models.DateTimeField(
                blank=True, help_text="Tanggal pembayaran dikonfirmasi", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Bayar di Tempat (COD/Tunai)"),
                    ("qris", "QRIS / Transfer Online"),
                ],
                default="cod",
                help_text="Metode pembayaran yang dipilih",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_proof",
            field=models.ImageField(
                blank=True,
                help_text="Upload bukti pembayaran (QRIS/Transfer)",
                null=True,
                upload_to="payment_proofs/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_address",
            field=models.TextField(help_text="Alamat lengkap pickup"),
        ),
        migrations.AlterField(
            model_name="order",
            name="price_total",
            field=models.DecimalField(
                decimal_places=2, help_text="Total harga setelah diskon", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="scheduled_pickup",
            field=models.DateTimeField(help_text="Jadwal pickup yang diminta"),
        ),
        migrations.AlterField(
            model_name="order",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Layanan utama yang dipilih",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total berat dalam kg",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Harga per unit/kg", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(
                blank=True, help_text="Jumlah untuk layanan per item", null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, help_text="Total harga item ini", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Berat untuk layanan per kilo",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentsetting",
            name="account_name",
            field=models.CharField(help_text="Nama pemilik rekening", max_length=100),
        ),
        migrations.AlterField(
            model_name="paymentsetting",
            name="account_number",
            field=models.CharField(help_text="Nomor rekening", max_length=50),
        ),
        migrations.AlterField(
            model_name="paymentsetting",
            name="bank_name",
            field=models.CharField(help_text="Nama bank", max_length=50),
        ),
        migrations.AlterField(
            model_name="paymentsetting",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Apakah pengaturan ini aktif"
            ),
        ),
        migrations.AlterField(
            model_name="paymentsetting",
            name="qris_image",
            field=models.ImageField(
                help_text="QR Code QRIS", upload_to="qris/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="promo",
            name="description",
            field=models.TextField(help_text="Deskripsi promo"),
        ),
        migrations.AlterField(
            model_name="promo",
            name="discount_amount",
            field=models.PositiveIntegerField(help_text="Nominal diskon"),
        ),
        migrations.AlterField(
            model_name="promo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="promo/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="promo",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Apakah promo aktif"),
        ),
        migrations.AlterField(
            model_name="promo",
            name="min_transaction",
            field=models.PositiveIntegerField(default=0, help_text="Minimal transaksi"),
        ),
        migrations.AlterField(
            model_name="promo",
            name="title",
            field=models.CharField(help_text="Judul promo", max_length=100),
        ),
        migrations.AlterField(
            model_name="userpromo",
            name="assigned_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Tanggal promo diberikan"
            ),
        ),
        migrations.AlterField(
            model_name="userpromo",
            name="is_used",
            field=models.BooleanField(
                default=False, help_text="Apakah promo sudah digunakan"
            ),
        ),
        migrations.AlterField(
            model_name="userpromo",
            name="promo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_promos",
                to="orders.promo",
            ),
        ),
        migrations.AlterField(
            model_name="userpromo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_promos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
