# Generated by Django 5.2.6 on 2026-07-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_userpromo_options_laundryitem_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Nomor order profesional (contoh: INV-2026/07/22-001)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
